import type { Metadata } from "next";
import CollectionsClient from "./CollectionsClient";

export const metadata: Metadata = {
  title: "Luxury Wedding Card Maker & Invitation Designer Collections | Mira Cards",
  description:
    "Browse Gujarati kankotri, luxury box invitations, foil, laser-cut and acrylic designs, plus coordinated wedding stationery. Serving Ahmedabad, Vadodara and Gandhinagar, with international delivery.",
  keywords: [
    "wedding card collections Surat",
    "luxury wedding invitation collections India",
    "box wedding invitation collection",
    "laser cut wedding card collection",
    "acrylic wedding invitation collection",
    "digital video invitation collection",
    "foil wedding card collection",
    "babyshower invitation collection",
    "Gujarati wedding invitation cards",
    "traditional Gujarati wedding cards",
    "Gujarati wedding card designs",
    "Indian marriage invitation cards",
    "traditional wedding invitation cards",
    "personalized marriage cards",
    "unique wedding invitation designs",
    "modern wedding invitation cards",
    "traditional wedding card designs",
    "handmade wedding invitation cards",
    "engagement invitation cards Ahmedabad",
    "engagement invitation design",
    "premium money envelopes",
    "wedding money envelopes",
    "wedding welcome boards Ahmedabad",
    "wedding welcome sign boards",
    "customized wedding stationery",
    "personalized wedding invitation suite",
    "wedding save the date cards",
    "personalized wedding logo",
    "wedding hashtag design",
    "wedding itinerary cards",
    "wedding RSVP cards",
    "wedding thank you cards",
    "wedding place cards",
    "wedding menu cards",
    "wedding gift tags",
    "wedding welcome notes",
    "personalized wedding stickers",
    "wedding invitation accessories",
    "wedding ceremony cards",
    "wedding gift packaging",
    "gold foil wedding invitations",
    "gold foiling wedding cards",
    "laser cut wedding cards",
    "acrylic wedding invitations",
    "velvet wedding invitation cards",
    "embossed wedding invitations",
    "premium foil printed wedding cards",
    "luxury wedding card printing",
    "customized box wedding cards",
    "premium wedding card finishing",
    "marriage invitation cards Gujarat",
    "Indian wedding cards online",
    "customized wedding cards online",
    "luxury wedding invitations India",
  ],
  alternates: {
    canonical: "https://miracards.in/collections",
  },
  openGraph: {
    url: "https://miracards.in/collections",
    title: "Luxury Wedding Card Maker & Invitation Collections | Mira Cards",
    description: "Browse bespoke wedding card collections. Custom designs shipped to India, USA, Australia & worldwide.",
    images: [{ url: "/og-image.jpg", width: 1200, height: 630, alt: "Mira Cards Invitation Collections" }],
  },
};

export default function CollectionsPage() {
  return <CollectionsClient />;
}
